add_executable(lc2235 lc2235.cpp)
add_executable(lc412 lc412.cpp)
add_executable(lc1480 lc1480.cpp)
add_executable(lc1929 lc1929.cpp)
add_executable(lc26 lc26.cpp)
add_executable(lc27 lc27.cpp)
add_executable(lc121 lc121.cpp)
add_executable(lc283 lc283.cpp)
add_executable(lc53 lc53.cpp)
add_executable(lc238 lc238.cpp)
add_executable(lc704 lc704.cpp)
add_executable(lc34 lc34.cpp)
add_executable(lc977 lc977.cpp)
add_executable(lc11 lc11.cpp)
add_executable(lc75 lc75.cpp)
add_executable(lc56 lc56.cpp)
add_executable(lc125 lc125.cpp)
add_executable(lc151 lc151.cpp)
add_executable(lc20 lc20.cpp)
add_executable(lc242 lc242.cpp)
add_executable(lc1 lc1.cpp)
add_executable(lc49 lc49.cpp)
add_executable(lc88 lc88.cpp)
add_executable(lc383 lc383.cpp)
add_executable(lc15 lc15.cpp)
add_executable(lc150 lc150.cpp)
add_executable(lc202 lc202.cpp)
add_executable(lc128 lc128.cpp)
add_executable(lc54 lc54.cpp)
add_executable(lc73 lc73.cpp)
add_executable(lc1337 lc1337.cpp)
add_executable(lc215 lc215.cpp)
